Method refactors and Removal of BinaryWriterEx/BinaryWriterFast
MontyTRC89/Tomb-Editor pull request #958
Opened 2024-11-23 13:34 UTC by Raildex

This PR adds some optimizations to Method arguments.
Namely using `in` for read-only arguments and using `Span<T>` with stack allocated intermediate buffers where possible.

Also removes `BinaryWriterEx`/`BinaryWriterFast` and `BinaryReaderEx`;
Functions for writing/reading are put into an Extension for `BinaryWriter`/`BinaryReader` instead.
`BinaryWriterEx` and `BinaryReaderEx` were simple subclasses with few additional methods for writing/reading Vectors and Arrays.
`BinaryWriterFast` was relying on unsafe contexts and did not have visible benefits in performance for writing.

2024-11-23 13:55 UTC, Nickelony requested changes
Looks good! Just one question and a few code style changes. :)

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/LevelData/Compilers/Rooms.cs
> +        private Vector3 CalculateLightForCustomVertex(Room room,in Vector3 position, in Vector3 normal, bool forImportedGeometry,in Vector3 ambientColor)
Please add a space before the first and third `in`

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/IO/BinaryWriterExtensions.cs
> +            try
Please keep an empty line before any `try` / `switch` / `if` / `for` / `foreach` / `do` or `while` block like this:
```cs
var sizeOfT = Marshal.SizeOf(typeof(T));
var unmanaged = Marshal.AllocHGlobal(sizeOfT);

try
{
    var buffer = new byte[sizeOfT];
    ...
```

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/IO/BinaryWriterExtensions.cs
> +            try
Same as above

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/LevelData/Compilers/TombEngine/TombEngine.cs
> +                using (var writer = new BinaryWriter(mediaStream,System.Text.Encoding.ASCII, true))
Please add a space before `System.Text.Encoding.ASCII`

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/LevelData/IO/Prj2Writer.cs
> +                //stream.Seek(0, SeekOrigin.Begin);
Why is this not needed anymore exactly? Please consider removing it completely if it's actually pointless.

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/Utils/Collision.cs
> +        public static bool RayIntersectsTriangle(in Ray ray,in Vector3 vertex1, in Vector3 vertex2,in Vector3 vertex3, bool bothSides, out Vector3 point)
Please add a space before the second and fourth `in`

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/Utils/Collision.cs
> +        public static PlaneIntersectionType PlaneIntersectsTriangle(in Plane plane, in Vector3 vertex1, in Vector3 vertex2,in Vector3 vertex3)
Please add a space before the last `in`

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/Utils/ImageC.cs
> +        public unsafe void CopyFrom(int toX, int toY,in ImageC fromImage, int fromX, int fromY, int width, int height)
Please add a space before the `in`

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/Utils/ImageC.cs
> +        public unsafe void ReplaceColor(in ColorC from,in ColorC to)
Please add space before the second `in`

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/Utils/ImageC.cs
> -
Like before, please always keep a space before any block declaration and after a block chain is finished (`if, else if, else`).

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/Utils/ImageC.cs
> +        public BlendMode HasAlpha(TRVersion.Game version,in Rectangle2 rect)
Add space before `in`

2024-11-23 13:55 UTC, Nickelony commented on TombLib/TombLib/Utils/ImageC.cs
> +        public void CopyFrom(int toX, int toY,in ImageC fromImage)
Add space before `in`

2024-11-24 14:01 UTC, Nickelony approved these changes

2024-11-27 21:16 UTC, Nickelony commented
That writer might've been faster in .NET 4.x, but now, this might not be the case anymore. That's my theory at least.

2025-02-21 07:48 UTC, Lwmte commented on TombLib/TombLib/LevelData/Compilers/TombEngine/TombEngine.cs
> +                using (var writer = new BinaryWriter(mediaStream, System.Text.Encoding.ASCII, true))
Why `System.Text.Encoding.ASCII` is used here? Old `BinaryWriterEx` was using `System.Text.Encoding.UTF8`.

2025-03-08 12:43 UTC, merged